apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastapi-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/fastapi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # must be empty for static binding

